version: '2'

services:
    # testing:
    #     container_name: testing
    #     build:
    #         context: ./testing
    #         dockerfile: node.dockerfile
    #     ports:
    #         - "3001:3000"
    #     working_dir: /var/www
    #     stdin_open: true
    #     command: >
    #         sh -c "npm run start"
    #     volumes:
    #       - ./testing:/var/www
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: node.dockerfile
        depends_on:
            - server
        ports:
            - "3002:3000"
        working_dir: /var/www
        stdin_open: true
        command: >
            sh -c "npm run start"
        volumes:
          - ./client:/var/www
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: node.dockerfile
        depends_on:
            - mongo
        ports:
            - "3090:3090"
        working_dir: /var/www
        volumes:
            - ./server:/var/www
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27018:27017"
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8082:8081
        # environment:
        #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
        #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
        #     ME_CONFIG_MONGODB_PORT: 27018
