# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c3190dc92eea83922ce1fe15d8d7ce18f7a024a48db6f9e4d5eeff15d75e8b2d463b132d2757e5f21a09b0ac6a5faf30800ffb324acd61fa3cf759aa9f1b319

test:
  secret_key_base: 47e3ceceef704beb4eb3e78ab7ef617c924160288771103e82501fbb96641a2cbde0f0540600bee5dbd1f05a35af814fec22434fe411a356e5bfe0c15ceb6df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
