name: CI

on:
  pull_request:
    branches: [develop]
    paths:
      - .github/**
      - 'udemy/AdvancedReactRedux/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: cd $PROJECT_HOME && npm ci
      - run: cd $PROJECT_HOME && npm run format:check
      - run: cd $PROJECT_HOME && npm test -- --coverage
        env:
          CI: true
          PROJECT_HOME: udemy/AdvancedReactRedux/testing/

            