name: CI

on:
  pull_request:
    branches: [develop]
    paths:
      - .github/**
      - 'udemy/AdvancedReactRedux/**'
  push:
    branches: [develop]
    paths:
      - .github/**
      - 'udemy/AdvancedReactRedux/**'

jobs:
  build:
    env:
      PROJECT_PATH: udemy/AdvancedReactRedux/testing/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
           ${{ runner.os }}-node- 
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: pwd
      - run: cd $PROJECT_PATH && npm ci
      - run: cd $PROJECT_PATH && npm run format:check
      - run: cd $PROJECT_PATH && npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: cd $PROJECT_PATH && npm run build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: cd $PROJECT_PATH && npx surge --project ./build --domain desertfoxdev.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

            