name: CI

on:
  pull_request:
    branches: [develop]
    # paths:
    #   - 'udemy/AdvancedReactRedux/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: cd udemy/AdvancedReactRedux/testing/ && npm ci
      - run: cd udemy/AdvancedReactRedux/testing/ && npm run format:check
      - run: cd udemy/AdvancedReactRedux/testing/ && npm test -- --coverage
        env:
          CI: true

            